### ISSUE TITLE
Broken TensorFlow installation

### ISSUE THREAD

**Issue by wlandau** [wlandau/targets-keras#3]
## Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targets-manual/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targets`' [contributing guidelines](https://github.com/wlandau/targets-manual/blob/master/CONTRIBUTING.md).

## Description

And as discussed at https://community.rstudio.com/t/installation-of-tensorflow-terminated-on-rstudio-cloud/75447/10, we need more than the available 1 GB of memory to install TensorFlow.

**Comment by wlandau-lilly** [comment]
Fixed
